### ISSUE TITLE
Add Awesome CTO Resources as a reference.

### ISSUE THREAD

**Issue by tcostam** [vintasoftware/playbook#41]
Add [Awesome CTO Resources](https://github.com/mateusz-brainhub/awesome-cto-resources) as a resource. I think it could go well under Project Management in a new section called Resources. Or maybe it'd go better under Culture, in a new section called the same.

What do you think @fjsj @laisvarejao @filipeximenes

**Comment by filipeximenes** [comment]
@tcostam maybe a Resources section in the "Technical Leadership" section fits better.
